var SMLIB_FW_WIDGET_RECOMMENDLIST_LOADER_LIST = JSON.parse('{"ITEMS":[]}');

//JQUERY
SMLIB_FW_WIDGET_RECOMMENDLIST_LOADER_LIST.ITEMS[SMLIB_FW_WIDGET_RECOMMENDLIST_LOADER_LIST.ITEMS.length] =
      JSON.parse('{"WIDGETNAME":"RECOMMENDLIST","WIDGETELEMENT":"SMLIBFWW_RECOMMENDLIST_JQUERY_STATICUSED","TYPE":"JQUERY","FILETYPE":"JS","VERSION":"2.0.0"}');
SMLIB_FW_WIDGET_RECOMMENDLIST_LOADER_LIST.ITEMS[SMLIB_FW_WIDGET_RECOMMENDLIST_LOADER_LIST.ITEMS.length] =
      JSON.parse('{"WIDGETNAME":"RECOMMENDLIST","WIDGETELEMENT":"SMLIBFWW_RECOMMENDLIST_JQUERY.min","TYPE":"JQUERY","FILETYPE":"JS","VERSION":"2.0.0"}');


//WIDGET
SMLIB_FW_WIDGET_RECOMMENDLIST_LOADER_LIST.ITEMS[SMLIB_FW_WIDGET_RECOMMENDLIST_LOADER_LIST.ITEMS.length] =
      JSON.parse('{"WIDGETNAME":"RECOMMENDLIST","WIDGETELEMENT":"SMLIBFWW_RECOMMENDLIST_W","TYPE":"WIDGET","FILETYPE":"JS","VERSION":"2.0.0"}');

//CSS
SMLIB_FW_WIDGET_RECOMMENDLIST_LOADER_LIST.ITEMS[SMLIB_FW_WIDGET_RECOMMENDLIST_LOADER_LIST.ITEMS.length] =
      JSON.parse('{"WIDGETNAME":"RECOMMENDLIST","WIDGETELEMENT":"SMLIBFWW_RECOMMENDLIST_CSS.min","TYPE":"CSS","FILETYPE":"CSS","VERSION":"2.0.0"}');

AttachWidgetContentList(SMLIB_FW_WIDGET_RECOMMENDLIST_LOADER_LIST);